/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ClientJNI */

#ifndef _Included_ClientJNI
#define _Included_ClientJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ClientJNI
 * Method:    request_token
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ClientJNI_request_1token
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
